typography_spectrum: 0.18196081230416894
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.5630961139686406
  lightness: 0.6545823225751519
  saturation: 0.07965900329872966
  rhythmicContrast: 0.2854336560703814
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.2919045148883015
analytics:
  google: null
  facebook: null
  twitter: null
name: Connections of Hope
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Connections of Hope
description: The Glenn T. Greenberg Foundation
purpose: []
